const Discord = require("discord.js");
const axios = require("axios");

module.exports = {
    name: "aes",
    async execute(message, args) {
        await axios({
            method: 'get',
            url: "https://fortnite-api.com/v2/aes"
        }).then(async function(response) {

            const date = new Date(response.data.data.updated)

            let text = `آخر تحديث في ${date.toLocaleDateString("ar-AR", { year: 'numeric', month: 'numeric', day: 'numeric', hour: 'numeric', minute: 'numeric' })}\n\n**MAIN**\`\`\`css\n${response.data.data.mainKey}\`\`\``;
            let textS = null;

            if(response.data.data.dynamicKeys !== null) {
                text += "\n\n** KEYS**\n";
                let e = 0;
                while(e != response.data.data.dynamicKeys.length) {
                    const test = `\n**${response.data.data.dynamicKeys[e].pakFilename}**\n\`\`\`fix\n${response.data.data.dynamicKeys[e].key}\`\`\``;
                    if((text.length + test.length) < 2048) text += test;
                    else textS += test;
                    e++
                }
            }

            if(textS != null) {
                const embed = new Discord.MessageEmbed()
                .setTitle(response.data.data.build)
                .setColor('#b6f711')
                .setDescription(text)
                .setFooter("Generated by BF8-Bot.", "https://cdn.discordapp.com/attachments/896619912288698379/896691819524538378/PicsArt_10-04-06.08.59.jpg")
                await message.channel.send(embed);

                embed.setFooter(message.author.username, message.author.displayAvatarURL({dynamic: true}))
                .setTitle('')
                .setTimestamp()
                .setDescription(textS)

                return message.channel.send(embed);
            } else {
                const embed = new Discord.MessageEmbed()
                .setColor('#b6f711')
                .setTitle(response.data.data.build)
                .setFooter(message.author.username, message.author.displayAvatarURL({dynamic: true}))
                .setTimestamp()
                .setDescription(text)

                return message.channel.send(embed);
            }
        })
    }
}