const Discord = require("discord.js");
const { Bot, Kevin } = require("..");

module.exports = {
    name: "help",
    execute(message, args) {
        const embed = new Discord.MessageEmbed()
        .setTitle("قائمة بلدي commandes")
        .setThumbnail(Bot.user.displayAvatarURL())
        .setColor('#bf9322')
        .addField("عام", `**${Kevin.Param.prefix}help** help for cmd ! 
        \n**${Kevin.Param.prefix}invite** invite bot !`)
        .addField("Blog", `**${Kevin.Param.prefix}blog** news`, true)
        .addField("Skins", `**${Kevin.Param.prefix}cos** skins`)
        .addField("Map", `**${Kevin.Param.prefix}map** map`, true)
        .addField("News", `**${Kevin.Param.prefix}news** news (\`br\`, \`cr\` ou \`stw\`)`, true)
        .addField("Shop", `**${Kevin.Param.prefix}shop** item shop in ar`, true)
        .addField("Stats", `**${Kevin.Param.prefix}stats** stats`, true)
        .addField("Status", `**${Kevin.Param.prefix}status** status of srver`, true)
        .addField("AES key", `**${Kevin.Param.prefix}aes** aes keys for (leaker)`, true)
        .addField("Leak", `**${Kevin.Param.prefix}leaks** new skins`, true)
        .setFooter("Generated by BF8-Bot.", "https://cdn.discordapp.com/attachments/896619912288698379/896691819524538378/PicsArt_10-04-06.08.59.jpg")
        .setTimestamp()
        return message.channel.send(embed);
    }
}
