const Discord = require("discord.js");

module.exports = {
    name: "invite",
    execute(message, args) {
        const embed = new Discord.MessageEmbed()
        .setDescription("**"+message.author.username+"**, invite my bot to your discord [invite](https://discord.com/api/oauth2/authorize?client_id=904155297340358676&permissions=322624&scope=bot) join my discord if you need any help [help](https://discord.gg/vjDfGrKY) ! <:BF8#2540:766811488547373056>")
        .setColor("#0078ff")
        .setTimestamp()
        .setFooter(`Commande faite par ${text='Generated by BF8-Bot.'}`, message.author.displayAvatarURL({dynamic: true}))
        return message.channel.send(embed);
    }
}