const Discord = require("discord.js");

module.exports = {
    name: "map",
    execute(message, args) {
        const embed = new Discord.MessageEmbed()
        .setTitle("Map Battle Royale")
        .setImage("https://fortnite-api.com/images/map_ar.png")
        .setFooter("Generated by BF8-Bot.", "https://cdn.discordapp.com/attachments/896619912288698379/896691819524538378/PicsArt_10-04-06.08.59.jpg")
        .setTimestamp()
        .setColor('#0078ff')
        return message.channel.send(embed);
    }
}