const Discord = require("discord.js");
const axios = require("axios");
const fs = require("fs");

const { generateNews, generateNewsSTW } = require('../functions/news.js')

module.exports = {
    name: "news",
    cooldown: 3,
    async execute(message, args, bot, prefix) {

        message.channel.startTyping()

        const embed = new Discord.MessageEmbed()
        .setColor('#0078ff')
        .setFooter("Generated by BF8-Bot.", "https://cdn.discordapp.com/attachments/896619912288698379/896691819524538378/PicsArt_10-04-06.08.59.jpg")
      
    
        if(!args.length || args[0] == 'br') {
            embed.setTitle(" Fortnite Battle Royale")
            fs.stat('./final/br-news.gif', async function(err, stats) {
                if(!err) {
                    embed.attachFiles('./final/br-news.gif')
                    .setImage('attachment://br-news.gif')
                }
                else {
                    const request = await axios({
                        method: 'get',
                        url: 'https://fortnitecontent-website-prod07.ol.epicgames.com/content/api/pages/fortnite-game',
                        headers: { 
                            'Accept-Language': 'ar-AR', 
                        }
                    })
                    if(request.data.battleroyalenewsv2.news.motds.length == 0) {
                        message.channel.stopTyping()
                        return message.reply("il n'y a actuellement aucune actualité en jeu")
                    }
                    await generateNews(request.data.battleroyalenewsv2).then(async (value) => {
                        embed.attachFiles(value)
                        .setImage('attachment://br-news.gif')
                    })
                }
                await message.channel.stopTyping()
                return await message.channel.send(embed)
            })
        } else if(args[0] == 'cr') {
            embed.setTitle("Actualités Fortnite Créatif")
            fs.stat('./final/creatif-news.gif', async function(err, stats) {
                if(!err) {
                    embed.attachFiles('./final/creatif-news.gif')
                    .setImage('attachment://creatif-news.gif')
                }
                else {
                    const request = await axios({
                        method: 'get',
                        url: 'https://fortnitecontent-website-prod07.ol.epicgames.com/content/api/pages/fortnite-game',
                        headers: { 
                            'Accept-Language': 'ar-AR', 
                        }
                    })
                    if(request.data.creativenewsv2.news.motds.length == 0) {
                        message.channel.stopTyping()
                        return message.reply("il n'y a actuellement aucune actualité en jeu")
                    }
                    await generateNews(request.data.creativenewsv2).then(async (value) => {
                        embed.attachFiles(value)
                        .setImage('attachment://creatif-news.gif')
                    })
                }
                await message.channel.stopTyping()
                return await message.channel.send(embed)
            })
        } else if(args[0] == 'stw') {
            embed.setTitle(" Fortnite Sauver le Monde")
            fs.stat('./final/stw-news.gif', async function(err, stats) {
                if(!err) {
                    embed.attachFiles('./final/stw-news.gif')
                    .setImage('attachment://stw-news.gif')
                }
                else {
                    const request = await axios({
                        method: 'get',
                        url: 'https://fortnitecontent-website-prod07.ol.epicgames.com/content/api/pages/fortnite-game',
                        headers: { 
                            'Accept-Language': 'ar-AR', 
                        }
                    })
                    if(request.data.savetheworldnews.news.messages.length == 0) {
                        message.channel.stopTyping()
                        return message.reply("لا توجد أخبار في اللعبة حاليًا")
                    }
                    await generateNewsSTW(request.data.savetheworldnews).then(async (value) => {
                        embed.attachFiles(value)
                        .setImage('attachment://stw-news.gif')
                    })
                }
                await message.channel.stopTyping()
                return await message.channel.send(embed)
            })
        } else {
            let embed = new Discord.MessageEmbed()
            .setTitle("Commande News")
            .setColor('#0078ff')
            .setDescription("فقط الأخبار \`br\`, \`cr\` et \`stw\` مدعمون !")
            .setFooter("Generated by BF8-Bot.", "https://cdn.discordapp.com/attachments/896619912288698379/896691819524538378/PicsArt_10-04-06.08.59.jpg")
            await message.channel.stopTyping()
            return await message.channel.send(embed)
        }
    }
}